### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by shesek**
- Uses the fantastic [`bitcoind`](https://crates.io/crates/bitcoind) crate by @RCasatta to setup a bitcoind regtest environment

- ~~Currently supports Bitcoin mode only, Liquid support is up next~~ (a similar `elementsd` crate exists to setup an elements regtest environment)
   
   Support for Liquid mode was added.

- Currently covers the HTTP REST API (some basic tests for 14 endpoints)  ~~, testing the Electrum RPC server will be added later - either with [`electrum_client`](https://docs.rs/electrum-client/latest/electrum_client/) to test the RPC commands directly, or more fully e2e with an headless Electrum wallet (I did the later before for [`bwt`](https://github.com/bwt-dev/bwt))~~

  The tests now cover the Electrum RPC server too.

- ~~I'm also looking to later implement e2e tests for the Esplora client-side web UI, using something like [`cypress`](https://www.cypress.io/).~~

   Available here: https://github.com/Blockstream/esplora/pull/362.

- Running with `JSONRPC_IMPORT=1` speeds up the initial indexing which can be useful for local development.

- CI integration is ~~still not~~ implemented via Github Actions.

### CODE REVIEW

**Comment by shesek** [comment]
Added e2e tests for the Electrum RPC server using the headless [Electrum wallet daemon](https://electrum.readthedocs.io/en/latest/jsonrpc.html) (96b7b0f3ac78a561daaa32e1f864b98a8a6bb317).

**Comment by shesek** [comment]
Added support for testing in Elements/Liquid mode in d62f582224cc43a22d31cce524fd1c48b8af0a53 and 25c7e9e2e5305e6558c47088f8b4de8a4f99fd50, including tests for Elements-specific functionality: CT, asset issuance and signed dynafed blocks.

Next up are tests for the esplora web ui.

**Comment by shesek** [comment]
Implemented e2e browser tests for the esplora web ui in https://github.com/Blockstream/esplora/pull/362.

**Review by piqjen-1xofFi-sikxyh — APPROVED** [review]

**Comment by shesek** [comment]
Rebased on top of #48.

**Comment by shesek** [comment]
Added Github Actions CI and rebased on top of #48.

Lacking further review, I will go ahead and merge this once #48 is in.

**Review by kentschumm — APPROVED** [review]

**Comment by shesek** [comment]
Reopened as #60.

**Pull request closed without merging**
