### PR TITLE
Allow looking up transactions via scripthash

### PR DESCRIPTION
**Pull request by shesek**
This adds the following new endpoints -

Lookup by the scriptpubkey hash:

- `GET /scripthash/:scripthash`
- `GET /scripthash/:scripthash/txs`
- `GET /scripthash/:scripthash/utxo`

~~Lookup by the scriptpubkey hex:~~

- ~~`GET /scriptpubkey/:scripthex`~~
- ~~`GET /scriptpubkey/:scripthex/txs`~~
- ~~`GET /scriptpubkey/:scripthex/utxo`~~

~~Lookup by the pubkey (p2pk only):~~

- ~~`GET /pubkey/:pubkey`~~
- ~~`GET /pubkey/:pubkey/txs`~~
- ~~`GET /pubkey/:pubkey/utxo`~~

### CODE REVIEW

**Comment by shesek** [comment]
I'm not really sure we really need `scriptpubkey` and `pubkey`, maybe just add `scripthash`?

**Comment by romanz** [comment]
> I'm not really sure we really need `scriptpubkey` and `pubkey`, maybe just add `scripthash`?

I agree - this way the backend logic will be simpler.

**Comment by shesek** [comment]
I force-pushed 16891ae00eeeb1a9c5cb5280ce8997aab25d52dc which removes lookup by scriptpubkey/pubkey and leaves just scripthash/address.

**Comment by shesek** [comment]
Cherry-picked to liquid_e in b631e3f.

**Comment by isghe** [comment]
Hi @shesek do you have any working example, I tried with https://blockstream.info/api/scripthash/0054c22ddfa26c9fd050414919dff5320c45a33e587c8e1f3e but I got a "502 Bad Gateway". Thanks :-)

**Comment by isghe** [comment]
@shesek solved! the input must be the sha256 of the hextobin of field `hex`.
Here a working example:

https://blockstream.info/api/scripthash/24720d8e1c30f12c14b928fa98f82fb58ea977d5ae119e8dec44ed8fde0e4242

:-)

**Pull request merged**
