### PR TITLE
Improved formatting for bitcoin'd rpc error messages

### LINKED ISSUE #132: TX post RPC errors not passed to client
When broadcasting a tx using POST to /tx, errors from the RPC request are not returned to the client; the client, including esplora, now only sees "RPC error":

client:

```
 % curl -X POST localhost:3001/tx
RPC error%                                                                   
```

electrs:
```
INFO handle POST /tx
DEBUG RPC HTTP 500 error: {"result":null,"error":{"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."},"id":179}
WARN HttpError(400, "RPC error")
```

This behaviour may have changed recently?

### PR DESCRIPTION
**Pull request by shesek**
Resolves #132.

### CODE REVIEW

**Comment by RCasatta** [comment]
LGTM, is it feasible to add a test asserting on error string in `tests/rest.rs` ?

**Comment by philippem** [comment]
I see the expected behaviour now, but  please add a test for this in `tests/rest.rs`

client:
```
% curl -X POST localhost:3001/tx
sendrawtransaction RPC error -22: TX decode failed. Make sure the tx has at least one input.%     
```

electrs:
```
INFO handle POST /tx
DEBUG RPC HTTP 500 error: {"result":null,"error":{"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."},"id":136}
WARN errors::Error: Error(RpcError(-22, "TX decode failed. Make sure the tx has at least one input.", "sendrawtransaction"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
WARN HttpError(400, "sendrawtransaction RPC error -22: TX decode failed. Make sure the tx has at least one input.")

```

**Review by philippem — DISMISSED** [review]

**Comment by shesek** [comment]
> is it feasible to add a test asserting on error string in `tests/rest.rs` ?

Yes, added in https://github.com/Blockstream/electrs/pull/133/commits/ee588140c52ea866555cfe57048089aeb9e0b147, including a test for a successful `POST /tx` request.

**Review by RCasatta — APPROVED** [review]
ack 4878e0a1f5a0028cf0a02a0e4a09584ff2a07040

**Pull request merged**
