### PR TITLE
fix: Abnormal return value from blockchain_scripthash_get_balance

### PR DESCRIPTION
**Pull request by fujicoin**
While the transaction is unconfirmed, blockchain_scripthash_get_balance returns a huge unconfirmed number.
The cause is the subtraction between u64.

ex)
```
{"id":"blk","jsonrpc":"2.0","result":{"confirmed":398056073100,"unconfirmed":18446743675653478516}}
```

### CODE REVIEW

**Comment by shesek** [comment]
Hi! Thanks for reporting this.

But I'm not quite sure I understand the bug and the fix.

For the `confirmed` balance, `chain_stats.spent_txo_sum` is guaranteed to be `<= chain_stats.funded_txo_sum`, so it should never overflow. In your example, the overflow was in the `unconfirmed` balance.

However, for the `unconfirmed` balance there already was an explicit conversion to i64, so it should've already worked?

**Comment by fujicoin** [comment]
@shesek 
ref: @cipig

I think the logic you are saying is correct.
However, in reality, overflow has occurred.
Therefore, we have to think that there is a bug in the rust compiler in the following formula.
```
"unconfirmed": mempool_stats.funded_txo_sum as i64 - mempool_stats.spent_txo_sum as i64,
```

The electrs binaries with this PR applied return a normal unconfirmed balance.

**Comment by fujicoin** [comment]
The cause of the confusion was found.
This issue has been fixed in commit bae4881.
fujicoin's electrs had forked before that and didn't reflect the bae4881 fix.

https://github.com/Blockstream/electrs/commit/bae488118de24d571042fb94e18789f0a9d1f69f

**Comment by shesek** [comment]
Oh right. Totally forgot about this :)

**Pull request closed without merging**
