### PR TITLE
Fix overlapping reads issue

### PR DESCRIPTION
**Pull request by junderw**
## The issue

1. There is one spot where a read lock is taken and while that read lock is still held a new read lock is taken recursively.
2. If the write thread tries to take the write lock between those two recursive reads, the write will wait for the first read to drop, then the second read will wait for the write to drop, but the first read won't drop until the code completes, which it can't because the second read is waiting on the lock....

It only happens occasionally, since the write lock is only taken every 15 seconds, and the problem only occurs IF the write TAKING is exactly between those two read lock takings, since they are pretty close, it's rare.

## Repro

1. Go to the liquid assets page
2. Hit the End key to scroll to bottom of the page
3. Click on a random page number in the pagination links at the bottom.
4. Repeat 2 and 3 at a rate of about 1 link click every 2 seconds at least.
5. After about 1-2 minutes the request will timeout, and the electrs process will deadlock. The GET request needs to be timed and coincide with the write() lock request.

---

## The issue

1. Every time you look up an asset, it calls `query.mempool()` which returns a RwLockReadGuard. Then later on (within a sub-function called with query passed in) `query.mempool()` is called again. This causes another possibility for the write() in the main loop (src/bin/electrs.rs) to occur between those two reads, causing the whole main loop to freeze.
2. The write() in the main loop must coincide with an asset GET request. The write() is called about once every 500 - 1500 ms. (500ms wait for user signal + the time it takes to query bitcoind for new blocks and mempool txs.)

### CODE REVIEW

**Comment by nitramiz** [comment]
Thanks for finding the actual bug! We've been having random issues with our Liquid Mainnet servers for a few weeks now. I discovered that sometimes after an API call to `/liquid/api/assets/registry` Electrs would stop responding to requests until it was restarted, but I was unable to debug into as much depth. 

Tested on [Esplora Staging](https://esplora.blockstream.com/liquid/assets) and can confirm that the issue is gone now. I followed your repro procedure and clicked back ~50 pages without breaking Esplora. And before I'd hit the bug after clicking back a few pages only.

**Comment by shesek** [comment]
Hi @junderw, appreciate the report and PR :pray: 

Your proposed fix for the mempool deadlock seems correct. Thanks for hunting this down!

However, I'm not sure that the `AssetRegistryLock` fix is necessary.

Note that `Query::list_registry_assets()` was previously calling `lookup_asset()` with `None` as the registry. This is because the metadata is already known (and provided as a `Some(meta)` in the last argument), so `lookup_asset()` doesn't have to use the registry to look it up again.

So there should be no overlapping locks of the `AssetRegistry`, even before this PR.

I believe the actual reason this PR fixed the issue is that it changed `lookup_asset()` to drop the read guard immediately after cloning the metadata.

A simpler fix based on that approach is available at https://github.com/Blockstream/electrs/compare/new-index...shesek:electrs:202307-fix-deadlock (in addition to dropping the lock sooner, it also avoids acquiring it in the first place in cases where its unnecessary).

---

You may be interested to know that I ended up implementing a `ReusableReadLock` trait-based approach that works similarly to your `AssetRegistryLock` runtime enum, before realizing it was (probably?) unnecessary. The code [is here](https://github.com/Blockstream/electrs/commit/5542b0ff3b73faf497375a1f3a3ba7d9a5446c5d) if want to check it out.

**Comment by junderw** [comment]
Looking back on it, we should consolidate registry and meta arguments into one argument.

```rust
enum AssetMetaGetter<'a> {
    Meta(&'a AssetMeta),
    Registry(&'a AssetRegistry),
    None,
}
```

Since the case of both being Some() does nothing in the logic.

Then we just need to take the lock before calling, and pass in a reference via the &RwLockReadGuard deref.

Or maybe just get rid of the None variant and wrap it in a Option...

**Comment by shesek** [comment]
> consolidate registry and meta arguments into one argument

I had a similar thought, but I'm not sure its worth it. Providing both arguments as `Some` is unnecessary, but it'll still do the right thing - use the provided metadata and ignore the registry (and with the changes in [my 202307-fix-deadlock branch](#58), will also avoid unnecessarily locking it).

**Pull request closed without merging**
